# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitProfiles' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitProfiles
  pod 'Kingfisher', '~> 7.0'
  target 'GitProfilesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitProfilesUITests' do
    # Pods for testing
  end

end
